// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtvbvbxaoy2dpQ9yxOjXOswAZkT_kUI5c',
    appId: '1:254554996237:web:1eeab8c0f9f3a9295c9f44',
    messagingSenderId: '254554996237',
    projectId: 'trust-id-63832',
    authDomain: 'trust-id-63832.firebaseapp.com',
    storageBucket: 'trust-id-63832.firebasestorage.app',
    measurementId: 'G-DTNT9Z2QQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByVXmgxEqog-fCCX6G70AR3tViEUMudPU',
    appId: '1:254554996237:android:5c32a8bb26f630805c9f44',
    messagingSenderId: '254554996237',
    projectId: 'trust-id-63832',
    storageBucket: 'trust-id-63832.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8iathuJFiwsTImfaDXNNQkLHLLhRpi7Y',
    appId: '1:254554996237:ios:67eaea1ecccdd31a5c9f44',
    messagingSenderId: '254554996237',
    projectId: 'trust-id-63832',
    storageBucket: 'trust-id-63832.firebasestorage.app',
    iosBundleId: 'com.example.identityFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8iathuJFiwsTImfaDXNNQkLHLLhRpi7Y',
    appId: '1:254554996237:ios:67eaea1ecccdd31a5c9f44',
    messagingSenderId: '254554996237',
    projectId: 'trust-id-63832',
    storageBucket: 'trust-id-63832.firebasestorage.app',
    iosBundleId: 'com.example.identityFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtvbvbxaoy2dpQ9yxOjXOswAZkT_kUI5c',
    appId: '1:254554996237:web:6e9192abea7271e45c9f44',
    messagingSenderId: '254554996237',
    projectId: 'trust-id-63832',
    authDomain: 'trust-id-63832.firebaseapp.com',
    storageBucket: 'trust-id-63832.firebasestorage.app',
    measurementId: 'G-BS0YE3Z0GL',
  );
}
